name: Deploy {{ lambda name }} function
on:
  push:
    paths:
      - '*/**'
jobs:
  Deploy-{{ lambda name }}-Lambda:
    name: deploy refresh_ecount_session_lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Test
        run: |
          go test -timeout 30s ./...
      - name: Build binary
        run: |
          cd lambda && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: {{ Lambda Function Name }}
          zip_file: lambda/deployment.zip
          memory_size: 128
          timeout: 30
          handler: main
          runtime: go1.x
